### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by Quantum-VSEPR** [Quantum-VSEPR/version-control#1]
I think it looks better if the main title is a bit mor eorange

The styling rule could be changed like this:

```css
h1 {
color:#efa82e;
}
```
